### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by edheltzel** [edheltzel/dotfiles#1]
- [x] Add Fonts
- [x] Update order of scripts
- [x] add ssh key before running `repos setup`
- [x] add `fisher` to fish install setup _(if possible)_

**Comment by edheltzel** [comment]
- [x] Break nvim config into multiple files

**Comment by edheltzel** [comment]
ended remove nvim from the setup - could adapt vim enough into my over-all workflow to be productive enough. 

Also ran into some really oddness with the vim in general. 
**shelved till later**
